# Generated by Django 3.2.11 on 2022-01-12 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('gender', models.TextField(max_length=20)),
                ('phoneno', models.TextField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.TextField(max_length=25)),
                ('address', models.TextField(max_length=150)),
                ('registration_time', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
