# Generated by Django 3.2.11 on 2022-01-12 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('gender', models.TextField()),
                ('phoneno', models.TextField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('address', models.TextField()),
                ('registration_time', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='procedurehistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.TextField()),
                ('body_site', models.TextField()),
                ('procedure_date', models.DateField(default=datetime.date.today)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='illnesshistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.TextField()),
                ('body_site', models.TextField()),
                ('severity', models.TextField()),
                ('illness_date_onset', models.DateTimeField(default=datetime.datetime.now)),
                ('illness_date_abatement', models.DateTimeField(default=datetime.datetime.now)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.TextField()),
                ('criticality', models.TextField()),
                ('type', models.TextField()),
                ('comment', models.TextField()),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
