# Generated by Django 4.0 on 2022-01-13 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorId', models.IntegerField()),
                ('specalist', models.TextField(max_length=50, null=True)),
                ('disease', models.TextField(max_length=50, null=True)),
                ('status', models.TextField(default='0')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
