# Generated by Django 4.0 on 2022-01-13 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointmentTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
