# Generated by Django 3.2.11 on 2022-01-19 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_appointment_appointmenttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
