# Generated by Django 3.2.11 on 2022-01-19 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_appointment_appointmenttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
