# Generated by Django 3.2.11 on 2022-01-12 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('specalist', models.TextField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phoneno', models.TextField(max_length=10, unique=True)),
                ('gender', models.TextField(max_length=10)),
                ('password', models.TextField(max_length=25)),
                ('clinic_address', models.TextField(max_length=150)),
                ('registration_time', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.doctor')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='procedurehistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.TextField()),
                ('body_site', models.TextField()),
                ('procedure_date', models.DateField(default=datetime.date.today)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.TextField()),
                ('problem_body_site', models.TextField()),
                ('severity', models.TextField()),
                ('date_time_onset', models.DateTimeField(default=datetime.datetime.now)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('prescriptionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.TextField()),
                ('form', models.TextField()),
                ('strength', models.IntegerField()),
                ('strength_unit', models.TextField()),
                ('diluent', models.TextField()),
                ('diluent_amount', models.IntegerField()),
                ('diluent_unit', models.TextField()),
                ('dosade_directions', models.TextField()),
                ('frequency', models.IntegerField()),
                ('frequency_unit', models.TextField()),
                ('interval', models.IntegerField()),
                ('interval_unit', models.TextField()),
                ('named_time_event', models.TextField()),
                ('exact_timing_critical', models.BooleanField()),
                ('prescriptionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='labreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_event', models.TextField()),
                ('lab_test_name', models.TextField()),
                ('lab_specimen_type', models.TextField()),
                ('lab_specimen_method', models.TextField()),
                ('lab_specimen_body_site', models.TextField()),
                ('lab_findings', models.TextField()),
                ('lab_document', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('diagnosticId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.diagnostic')),
            ],
        ),
        migrations.CreateModel(
            name='imagingexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imaging_event', models.TextField()),
                ('imaging_test_name', models.TextField()),
                ('imaging_modality', models.TextField()),
                ('imaging_body_site', models.TextField()),
                ('imaging_findings', models.TextField()),
                ('imaging_document', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('diagnosticId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.diagnostic')),
            ],
        ),
        migrations.CreateModel(
            name='illnesshistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.TextField()),
                ('body_site', models.TextField()),
                ('severity', models.TextField()),
                ('illness_date_onset', models.DateTimeField(default=datetime.datetime.now)),
                ('illness_date_abatement', models.DateTimeField(default=datetime.datetime.now)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='doctorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.doctor'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.CreateModel(
            name='allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.TextField()),
                ('criticality', models.TextField()),
                ('type', models.TextField()),
                ('comment', models.TextField()),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
