# Generated by Django 4.0 on 2022-01-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='diluent_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='strength',
            field=models.IntegerField(default=0),
        ),
    ]
