# Generated by Django 3.2.11 on 2022-01-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_alter_medicines_diluent_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingexam',
            name='imaging_document',
            field=models.FileField(null=True, upload_to='static/images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='lab_document',
            field=models.FileField(null=True, upload_to='static/images/', verbose_name=''),
        ),
    ]
